name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install --ignore-scripts
      - run: npm run prebuild
      - uses: actions/upload-artifact@v2
        with:
          name: linux-x64
          path: prebuilds/linux-x64/
  build-win32-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install --ignore-scripts
      - run: npm run prebuild
      - uses: actions/upload-artifact@v2
        with:
          name: win32-x64
          path: prebuilds/win32-x64/
  build-darwin-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install --ignore-scripts
      - run: npm run prebuild
      - uses: actions/upload-artifact@v2
        with:
          name: darwin-x64
          path: prebuilds/darwin-x64/
  publish-npm:
    runs-on: ubuntu-latest
    needs: [build-linux-x64, build-win32-x64, build-darwin-x64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - uses: actions/download-artifact@v2
        with:
          path: prebuilds/
      - run: npm install
      - run: npm run build-ts
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
